### PR TITLE
doc / additional content on how to enable debug console on docker

### PR DESCRIPTION
**Pull request by john-hummingbot-support**
image

### CODE REVIEW

**Comment by JeremyKono** [comment]
Please follow the proper naming of the PRs

**Comment by john-hummingbot-support** [comment]
Updated @JeremyKono

**Comment by JeremyKono** [comment]
unrelated commit

image

**Comment by john-hummingbot-support** [comment]
I included the package-lock.json on the .gitignore file so once this PR gets merge anybody who pulled the update or setting up a new branch, won't have to keep excluding the package-lock.json file when they're doing commits or PR's.

**Pull request merged**
