### PR TITLE
cleanup / docs-sites

### PR DESCRIPTION
**Pull request by cali-tomas**
Fixed broken links 
- Check Bot and Market Status - Binance
- V.33 - documentation
- V.05 - Wallet import/export
image
image
image

### CODE REVIEW

**Comment by ralphemersonic** [comment]
before we merge can we correct the typo error e in the "arguement". Thanks.

msedge_8hFslbdeAg

**Comment by JeremyKono** [comment]
This is not yet to be merged @ralphemersonic We'll ping you if we have finished the project. Thanks

**Comment by ralphemersonic** [comment]
> This is not yet to be merged @ralphemersonic We'll ping you if we have finished the project. Thanks

Alright. Just let me know if I can help.

**Comment by dennisocana** [comment]
@JeremyKono @cali-tomas if the PR is not ready for review, convert it as draft

**Comment by JeremyKono** [comment]
Thanks. Converted the PR to draft

**Review by ralphemersonic — APPROVED** [review]

**Pull request merged**
