### PR TITLE
Docs/redo warning callouts

### PR DESCRIPTION
**Pull request by mikey084**
React Component for callouts, types: success, warning, danger, info, bug, quote. Takes in 4 props: type (callout type), body, link, linkName. Can leave link and linkName blank if no link required in body. Can use `` to surround text in your body input string for highlight, OR you can use ## to surround text in your input body to bold. 

Example: 
```
<Callout type="warning" body="#Binance# Perpetual connector is released as `beta version(0.33)`, trade it with your own risk. #Binance Perpetual is different from futures contract#, please see" link="https://www.binance.com/en/support/faq/360033524991" linkName="differences"/>
```

image

Other Callout types:

image

### CODE REVIEW

**Review by carlolm — CHANGES_REQUESTED** [review]
Is it possible to use some kind of icon library rather than emojis?
The emojis don't look very polished/professional:

image

**Comment by mikey084** [comment]
fixed some css, and added react-icon library

image

**Comment by mikey084** [comment]
fixed up css, added extra identifier edge case handle

image

**Comment by carlolm** [comment]
Thanks @mikey084 looks good to me

**Pull request merged**
